### ISSUE TITLE
Switch to university Ldap

### ISSUE THREAD

**Issue by Rado996** [fri-team/Swapify#577]
Switch from only  using fri ldap to uniza ldap.

**Comment by marektavac** [comment]
Uniza ldap server dc3.uniza.sk

**Comment by Flacore** [comment]
In last meeting we speak about create scenario for migration to university LDAP [user with fri ldap]. The application check user credentials from ldap so in this case we don't need to change anything. After successful check of credentials in LDAP we check if we have user with details in DB. Only needed change is for student email.

![UnizaLDAP drawio](https://user-images.githubusercontent.com/44835476/166217692-b0a88c1f-08ed-46dd-bdcf-bd8453356487.png)

@Rado996, @marektavac

**Comment by marektavac** [comment]
Very nice and clear, perfect job...
What will be the popup message for wrong password?

Is it possible to find out, when login not passed, that such user exists? Just password is wrong? (or is not so important, because it will not be very often?) - goal = to show the message about LDAP change just to existing users

**Comment by Flacore** [comment]
It`s actually possible without programing anything extra, thanks to function GetUserByEmailAsync defined in class UserService. In case when user don`t pass ldap login we can check if there is user with email [login]@fri.uniza.sk. If this user exist and doesn`t pass logging it would be probably because of wrong password (using old password from fri ldap).

**Comment by Flacore** [comment]
Its actually possible without programing anything extra, thanks to function GetUserByEmailAsync defined in class UserService. In case when user dont pass ldap login we can check if there is user with email [login]@fri.uniza.sk. If this user exist and doesn`t pass logging it would be probably because of wrong password (using old password from fri ldap).
