### ISSUE TITLE
[Teacher] research of printed teacher's timetables

### ISSUE THREAD

**Issue by barbierikovadom** [fri-team/Swapify#611]
Explore printed versions of teacher's timetables. Compare the outcome with our own printed version of timetable and suggest a redesign.

**Comment by PatrikCader27** [comment]
After the exploration of popular forms of timetables among teachers it was discovered there are two versions that are frequently used. 

![oldvsnew_print](https://user-images.githubusercontent.com/117161026/199387303-68436b36-5c6b-4781-ba28-c7c2b6171792.jpg)

**1. Redesign from horizontal to wide angle**
In this case, the wall-mounted holder for timetables should be our decisive input. If teachers are going to use our timetable, they wouldn't change the holder because of us. Presumably, we should go for 16:9 or 16:10 aspect ratio - as close to the holder as possible.

**2. Adding colors**
Timetables that are teacher's currently using are colorful for better arrangement and visibility. Our current printed version of timetable is black and white. We should go for readable and non-aggressive color pallet.


Proposed solution we discussed at standup is that we would print the default timetable straight out, just with larger font size by 2 or 4 points for better visibility from distance.
